import { basename } from "node:path";

/** Not a substring of `vicinae-hyprland-settings`, so the two hooks can coexist. */
export const PLUGIN_SWITCH_MARKER = "vicinae-plugin-switch";

export type DisabledPlugin = {
  name: string;
  path: string;
  description: string;
  author: string;
  version: string;
};

/**
 * hyprctl splits `plugin load` / `plugin unload` on spaces, and the skip file
 * is a Lua string. Reject paths that cannot survive both.
 */
export function isSafePluginPath(path: string): boolean {
  if (!path.startsWith("/")) return false;
  if (path.includes("\0") || /[\r\n"]/.test(path) || /\s/.test(path)) {
    return false;
  }
  return path.includes(".so");
}

/** First line of `$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/hyprland.lock`. */
export function pidFromLock(text: string): number | null {
  const line = text.split(/\r?\n/, 1)[0]?.trim() ?? "";
  if (!/^[1-9]\d*$/.test(line)) return null;
  const pid = Number(line);
  if (!Number.isSafeInteger(pid)) return null;
  return pid;
}

/** Shared-library paths from `/proc/<pid>/maps`. The path starts at the first slash. */
export function soPathsFromMaps(text: string): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const line of text.split("\n")) {
    const slash = line.indexOf("/");
    if (slash < 0) continue;
    const path = line.slice(slash).trim().replace(/ \(deleted\)$/, "");
    if (!path.includes(".so") || seen.has(path)) continue;
    seen.add(path);
    out.push(path);
  }
  return out;
}

function norm(value: string): string {
  return value.toLowerCase().replace(/[^a-z0-9]/g, "");
}

/** `hyprgrass` and `hypr-dynamic-cursors.so` both drop a leading `hypr`. */
export function pluginKey(name: string): string {
  const folded = norm(name);
  const stripped = folded.replace(/^hypr/, "");
  return stripped || folded;
}

export function soKey(path: string): string {
  const stem = basename(path).replace(/\.so(\.\d+)*$/, "");
  return pluginKey(stem);
}

/**
 * Pair each plugin name with one .so. A name with zero or several matches
 * stays unset so the screen does not unload the wrong file.
 */
export function matchPluginPaths(
  names: readonly string[],
  soPaths: readonly string[],
): Record<string, string | null> {
  const unused = [...soPaths];
  const matched: Record<string, string | null> = {};
  for (const name of names) {
    const key = pluginKey(name);
    const hits = unused.filter((path) => soKey(path) === key);
    const only = hits.length === 1 ? hits[0] : undefined;
    if (only && isSafePluginPath(only)) {
      matched[name] = only;
      const index = unused.indexOf(only);
      if (index >= 0) unused.splice(index, 1);
    } else {
      matched[name] = null;
    }
  }
  return matched;
}

function fileName(path: string): string {
  const name = basename(path);
  return name || path;
}

/**
 * Skip `hl.plugin.load` when the path is listed, or when it is the only
 * skipped file with that basename. Config often passes a different string
 * than the path in `/proc/pid/maps` (symlink, or `$HOME` joined in Lua).
 * The hook in `pluginSwitchHookBlock` must follow this rule.
 */
export function shouldSkipPluginPath(
  requested: string,
  skipped: readonly string[],
): boolean {
  if (skipped.includes(requested)) return true;
  const name = fileName(requested);
  const hits = skipped.filter((path) => fileName(path) === name);
  return hits.length === 1;
}

function quoteLua(path: string): string {
  return `"${path.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

export function renderDisabledPluginsLua(
  disabled: Record<string, { path: string }>,
): string {
  const paths = Object.keys(disabled)
    .filter((path) => isSafePluginPath(path))
    .sort();
  const lines = paths.map((path) => `  [${quoteLua(path)}] = true,`);
  return [
    "-- Generated by Vicinae Hyprland Settings. Do not edit.",
    "-- hl.plugin.load skips these paths so a reload does not bring them back.",
    "return {",
    ...lines,
    "}",
    "",
  ].join("\n");
}

export function pluginSwitchHookBlock(): string {
  return [
    `-- ${PLUGIN_SWITCH_MARKER}: skip plugins turned off in Hyprland Settings`,
    "do",
    '  local xdg = os.getenv("XDG_CONFIG_HOME") or ((os.getenv("HOME") or "/home/user") .. "/.config")',
    '  local ok, skipped = pcall(dofile, xdg .. "/hypr/vicinae-plugins.lua")',
    '  if ok and type(skipped) == "table" and hl and hl.plugin and type(hl.plugin.load) == "function" then',
    "    local load = hl.plugin.load",
    "    local function base(path)",
    '      return path:match("([^/]+)$") or path',
    "    end",
    "    local function blocked(path)",
    "      if skipped[path] then",
    "        return true",
    "      end",
    "      local name = base(path)",
    "      local hits = 0",
    "      for skipped_path, on in pairs(skipped) do",
    "        if on and type(skipped_path) == \"string\" and base(skipped_path) == name then",
    "          hits = hits + 1",
    "        end",
    "      end",
    "      return hits == 1",
    "    end",
    "    function hl.plugin.load(path)",
    '      if type(path) == "string" and blocked(path) then',
    "        return",
    "      end",
    "      return load(path)",
    "    end",
    "  end",
    "end",
  ].join("\n");
}

/** Prepend the load wrapper. No-op once the marker is present. */
export function withPluginSwitchHook(existing: string): string {
  if (existing.includes(PLUGIN_SWITCH_MARKER)) return existing;
  const block = pluginSwitchHookBlock();
  if (existing.length === 0) return `${block}\n`;
  return `${block}\n\n${existing}`;
}
